### ISSUE TITLE
DCS renders the right eye incorrectly with FFR turned on (RDM)

### ISSUE THREAD

**Issue by Canoe23** [RavenSystem/VRPerfKit_RSF#2]
DCS renders the right eye incorrectly with FFR enabled, using RDM. Attached is a screenshot from the oculus mirror, which is the same view I get through the lenses, a screenshot from the game mirror showing the right lens, which is a bit different than what I get through the lens, and my config file (as a txt to keep github happy). I am using an AMD RX6600 with an Oculus Quest 1 if that changes anything. The issues occur with link, as I can't get DCS to use steamvr instead of the oculus runtime. 

![image](https://github.com/RavenSystem/VRPerfKit_RSF/assets/59153933/7aac69ab-c474-4b6c-9538-5ffc2e2ecf80)
![image](https://github.com/RavenSystem/VRPerfKit_RSF/assets/59153933/bfc26aa6-d7f2-470a-9805-2e8804e221a8)
[vrperfkit_RSF.txt](https://github.com/RavenSystem/VRPerfKit_RSF/files/13848122/vrperfkit_RSF.txt)

**Comment by RavenSystem** [comment]
Try changing gameMode to left.

**Comment by Canoe23** [comment]
Issue is unchanged when set to left, when set to right it is instead mirrored onto the left eye, and when set to single it is on both eyes, but looks a bit different. Attached is a screenshot when set to single.
![image](https://github.com/RavenSystem/VRPerfKit_RSF/assets/59153933/40ec7e7c-40e1-492c-bfd4-b592144c9f37)

**Comment by RavenSystem** [comment]
Game seems to be `gameMode: left`. You must play with these parameters into `fixedFoveated:` section to find the right target render:
```
renderOnlyTarget: 0
ignoreFirstTargetRenders: 0
ignoreLastTargetRenders: 0
```

A start point could be using `renderOnlyTarget: -1`

**Comment by Canoe23** [comment]
`renderOnlyTarget: -1 `and `gameMode: single` were correct for dcs, thank you for the help.

**Comment by RavenSystem** [comment]
@Canoe23 Please, could you tell me how is DCS performance with RDM?

**Comment by Canoe23** [comment]
It's strange, I have some more tuning to do but it looks buttery smooth in the menus, once I load into a server it drops down to around 4-6 fps with 100% gpu usage. This persists even once I leave the server and go back to the main menu so I'm not sure what's causing it.

**Comment by RavenSystem** [comment]
It is possible that toolkit is not allowed to be used in multiplayer because it uses hook/injectors, and cheats use hook/injectors too.

**Comment by Canoe23** [comment]
It's allowed and it works, it just drops my fps to 4-6 and locks gpu usage to 100%, even when returning to menus.
